### ISSUE TITLE
runcommand-onstart.sh bracket missing

### ISSUE THREAD

**Issue by chipsnblip** [Sakitoshi/retropie-crt-tvout#19]
hello there.  i was poking around a bit and noticed a line in _/dev/shm/runcommand.log_

> /opt/retropie/configs/all/runcommand-onstart.sh: line 3: [: missing `]'

tried a couple of methods to quiet this warning and both seem to work fine:

`if [ ! -s "/opt/retropie/configs/$1/480i.txt" ] && [ ! -s "/opt/retropie/configs/ports/$1/480i.txt" ]`

`if [[ ! -s "/opt/retropie/configs/$1/480i.txt" && ! -s "/opt/retropie/configs/ports/$1/480i.txt" ]]
`
not a big deal or anything, just thought you'd want to know about it.

kind regards,
chipsnblip

**Comment by Sakitoshi** [comment]
nice catch.
fixed #20
