### ISSUE TITLE
Open Tyrian can be optimized for 240p?

### ISSUE THREAD

**Issue by RFleury** [Sakitoshi/retropie-crt-tvout#35]
Open Tyrian has vertical tearing. Open Tyrian can be optimized for 240p?

**Comment by Sakitoshi** [comment]
that's out of my hand and out of the scope of the project.
I can merely adjust the output to match how it looked on real hardware and only if is a libretro core, not fix problems with ports.

**Comment by RFleury** [comment]
ok thanks anyway, your work on this project is precious, a beautiful job.
