### ISSUE TITLE
update comment in to_config.txt

### ISSUE THREAD

**Issue by chipsnblip** [Sakitoshi/retropie-crt-tvout#42]
happy new year, Sakitoshi.  i just noticed the comment on lines 10 & 11 of master/to_config.txt states _-yres 400_, but should it be _448_ now?

a bit off-topic but lately i've been experimenting with framebuffer resolutions on my 13" crt tv, trying to find a good compromise between aspect ratio, overscan, and readability. 400x280 seems to be a happy medium, but i wonder if there is truly a golden ratio that has yet to be discovered :)

**Comment by Sakitoshi** [comment]
yeah, a small typo considering that is only a comment, the idea gets across.
I have a 14" display myself and 400x280 is too big.

I updated the file anyway with a better horizontal resolution though.
