### ISSUE TITLE
Save Retroarch problem.

### ISSUE THREAD

**Issue by RFleury** [Sakitoshi/retropie-crt-tvout#44]
I believe it is not a problem with your project, but this has never happened to me before until the moment I update with its new version, I am not able to make changes to the Retroarch settings, even using Save Overrides. I need to make specific changes to the audio, core options, and other visual customizations of Retroarch, and when I save them, even using Save overrides when I come back, everything is default.

**Comment by Sakitoshi** [comment]
this configurations do nothing about how retroarch saves the settings and overrides work correctly (I've tested many times since I use overrides for certain games).
so the cause has to lie somewhere else.
