### ISSUE TITLE
retroarch setting sdtv mode back to boot default

### ISSUE THREAD

**Issue by b0xspread** [Sakitoshi/retropie-crt-tvout#45]
Please see https://retropie.org.uk/forum/topic/25938/retroarch-and-240p-on-crt-tv for full description

**Comment by Sakitoshi** [comment]
sorry, I can't help you with that as I don't own a raspi 4 to reproduce the issue (and of course not a problem with this configs that are designed for raspi 3).

**Comment by b0xspread** [comment]
@Sakitoshi no worries
